
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sun Jun 29 09:23:05 CST 2014
//----------------------------------------------------

package com.github.ceFractal.compiler.fractal;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int PR = 47;
  public static final int BTHAN = 29;
  public static final int MULT = 41;
  public static final int CHAR = 54;
  public static final int PL = 46;
  public static final int KW_INT = 2;
  public static final int Q = 62;
  public static final int KW_FOR = 10;
  public static final int KW_DO = 9;
  public static final int KW_CHAR = 4;
  public static final int INT = 52;
  public static final int REF = 51;
  public static final int MINUS = 40;
  public static final int KW_STATIC = 63;
  public static final int KW_PRIVATE = 20;
  public static final int KW_CASE = 16;
  public static final int BETHAN = 30;
  public static final int NOT = 36;
  public static final int AND = 34;
  public static final int LTHAN = 31;
  public static final int DMINUS = 39;
  public static final int LR = 59;
  public static final int KW_ARRAY = 66;
  public static final int OR = 35;
  public static final int BOOL = 55;
  public static final int DIEQUAL = 27;
  public static final int MIEQUAL = 25;
  public static final int LL = 58;
  public static final int DIV = 42;
  public static final int PLUS = 38;
  public static final int KW_NEW = 7;
  public static final int EXP = 43;
  public static final int ID = 56;
  public static final int KW_BOOL = 6;
  public static final int LETHAN = 32;
  public static final int KW_CONTINUE = 11;
  public static final int KW_RETURN = 61;
  public static final int EOF = 0;
  public static final int KW_CLASS = 18;
  public static final int EQUAL = 23;
  public static final int error = 1;
  public static final int KW_THIS = 67;
  public static final int COMA = 48;
  public static final int MUEQUAL = 26;
  public static final int NEWLINE = 64;
  public static final int NULL = 69;
  public static final int DEQUAL = 28;
  public static final int KW_SWITCH = 15;
  public static final int KW_IF = 13;
  public static final int ERROR = 65;
  public static final int KW_IMPORT = 22;
  public static final int KW_SUPER = 68;
  public static final int QR = 45;
  public static final int KW_VOID = 60;
  public static final int PUNTO = 50;
  public static final int KW_BREAK = 12;
  public static final int QL = 44;
  public static final int KW_PUBLIC = 19;
  public static final int NEQUAL = 33;
  public static final int FLOAT = 53;
  public static final int KW_ELSE = 14;
  public static final int PEQUAL = 24;
  public static final int DPLUS = 37;
  public static final int DPUNTOS = 49;
  public static final int KW_STRING = 5;
  public static final int STRING = 57;
  public static final int KW_DEFAULT = 17;
  public static final int KW_WHILE = 8;
  public static final int KW_EXTENDS = 21;
  public static final int KW_FLOAT = 3;
}

