
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140220
// Sat Jun 07 21:01:55 CST 2014
//----------------------------------------------------

package com.github.ceFractal.compiler.pj;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int TAGf = 6;
  public static final int TAGe = 7;
  public static final int EQUAL = 4;
  public static final int TAGi2 = 8;
  public static final int EOF = 0;
  public static final int STRING = 3;
  public static final int ID = 2;
  public static final int error = 1;
  public static final int TAGi = 5;
}

