package com.github.ceFractal.gui;

import com.github.ceFractal.compiler.fractal.Scanner.SSymbol;
import com.github.ceFractal.compiler.fractal.Sym;
import com.github.ceFractal.compiler.pj.Parser;
import com.github.ceFractal.compiler.pj.Scanner;
import com.github.gg.CC;
import com.github.gg.Dict;
import com.github.gg.Err;
import com.github.gg.Node;
import com.github.gg.Operation;
import com.github.gg.Sim;
import com.github.gg.TErr;
import com.github.gg.TModifier;
import com.github.gg.TOperation;
import com.github.gg.TType;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.StringReader;
import java.io.UnsupportedEncodingException;
import java.nio.charset.Charset;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import java_cup.runtime.Symbol;
import javax.swing.JEditorPane;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.JTree;
import javax.swing.SwingUtilities;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.AbstractDocument;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.BoxView;
import javax.swing.text.ComponentView;
import javax.swing.text.DefaultStyledDocument;
import javax.swing.text.Document;
import javax.swing.text.Element;
import javax.swing.text.IconView;
import javax.swing.text.LabelView;
import javax.swing.text.ParagraphView;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyleContext;
import javax.swing.text.StyledDocument;
import javax.swing.text.StyledEditorKit;
import javax.swing.text.TabSet;
import javax.swing.text.TabStop;
import javax.swing.text.View;
import javax.swing.text.ViewFactory;
import javax.swing.text.html.HTML;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeCellRenderer;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreeModel;
import javax.swing.tree.TreePath;

/**
 *
 * @author ce
 */
public class Win extends javax.swing.JFrame {

    /**
     * Creates new form Win
     */
    public Win() {
        initComponents();
        myinit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpumenu_pumenu = new javax.swing.JPopupMenu();
        jmitem_setactive = new javax.swing.JMenuItem();
        jsplitp_base1 = new javax.swing.JSplitPane();
        jsplitp_base2 = new javax.swing.JSplitPane();
        jtabbedp_tab = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jepane_console = new javax.swing.JEditorPane();
        jsp_tree_scroll = new javax.swing.JScrollPane();
        jtree_tree = new javax.swing.JTree();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newProMenuItem = new javax.swing.JMenuItem();
        newMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        openProMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        saveMenuItem = new javax.swing.JMenuItem();
        saveAsMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        comilerMenu = new javax.swing.JMenu();
        jmitem_compile = new javax.swing.JMenuItem();
        jmitem_tabsim = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jmitem_exec = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jmitem_errores = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsMenuItem = new javax.swing.JMenuItem();
        aboutMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        cutMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();
        pasteMenuItem = new javax.swing.JMenuItem();
        deleteMenuItem = new javax.swing.JMenuItem();

        jmitem_setactive.setText("SET ACTIVE");
        jmitem_setactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_setactiveActionPerformed(evt);
            }
        });
        jpumenu_pumenu.add(jmitem_setactive);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jsplitp_base2.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jsplitp_base2.setTopComponent(jtabbedp_tab);

        jScrollPane1.setViewportView(jepane_console);

        jsplitp_base2.setRightComponent(jScrollPane1);

        jsplitp_base1.setRightComponent(jsplitp_base2);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("PJ");
        jtree_tree.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jsp_tree_scroll.setViewportView(jtree_tree);

        jsplitp_base1.setLeftComponent(jsp_tree_scroll);

        getContentPane().add(jsplitp_base1, java.awt.BorderLayout.CENTER);

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        newProMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        newProMenuItem.setText("New Project");
        newProMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newProMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newProMenuItem);

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setText("New");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newMenuItem);
        fileMenu.add(jSeparator1);

        openProMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        openProMenuItem.setMnemonic('o');
        openProMenuItem.setText("Open Project");
        openProMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openProMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openProMenuItem);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setMnemonic('o');
        openMenuItem.setText("Open");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openMenuItem);
        fileMenu.add(jSeparator3);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        saveMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(saveMenuItem);

        saveAsMenuItem.setMnemonic('a');
        saveAsMenuItem.setText("Save As ...");
        saveAsMenuItem.setDisplayedMnemonicIndex(5);
        fileMenu.add(saveAsMenuItem);
        fileMenu.add(jSeparator2);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        comilerMenu.setText("Compiler");

        jmitem_compile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jmitem_compile.setText("Compilar");
        jmitem_compile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_compileActionPerformed(evt);
            }
        });
        comilerMenu.add(jmitem_compile);

        jmitem_tabsim.setText("Tabla de Simbolos");
        jmitem_tabsim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_tabsimActionPerformed(evt);
            }
        });
        comilerMenu.add(jmitem_tabsim);
        comilerMenu.add(jSeparator5);

        jmitem_exec.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
        jmitem_exec.setText("Ejecutar");
        comilerMenu.add(jmitem_exec);

        jMenuItem2.setText("Generar Codigo");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        comilerMenu.add(jMenuItem2);

        jMenuItem4.setText("Optimizar");
        comilerMenu.add(jMenuItem4);
        comilerMenu.add(jSeparator4);

        jmitem_errores.setText("Errores");
        jmitem_errores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmitem_erroresActionPerformed(evt);
            }
        });
        comilerMenu.add(jmitem_errores);

        jMenuItem5.setText("Errores Lexicos");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        comilerMenu.add(jMenuItem5);

        jMenuItem6.setText("Error Sintacticos");
        comilerMenu.add(jMenuItem6);

        jMenuItem7.setText("Error Sematicos");
        comilerMenu.add(jMenuItem7);

        menuBar.add(comilerMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Help");

        contentsMenuItem.setMnemonic('c');
        contentsMenuItem.setText("Contents");
        helpMenu.add(contentsMenuItem);

        aboutMenuItem.setMnemonic('a');
        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Edit");

        cutMenuItem.setMnemonic('t');
        cutMenuItem.setText("Cut");
        editMenu.add(cutMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Copy");
        editMenu.add(copyMenuItem);

        pasteMenuItem.setMnemonic('p');
        pasteMenuItem.setText("Paste");
        editMenu.add(pasteMenuItem);

        deleteMenuItem.setMnemonic('d');
        deleteMenuItem.setText("Delete");
        editMenu.add(deleteMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void jmitem_tabsimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_tabsimActionPerformed
        // TODO add your handling code here:

        WinTableDialog wintable = new WinTableDialog(this, false);
        final JTable table = wintable.getJtable_table();

        wintable.getJbutton_refresh().addActionListener((ActionEvent e) -> {
            refresh_symtable(table);
        });

        refresh_symtable(table);

//        wintable.setJtable_table(new JTable(data, headers));
        wintable.setVisible(true);


    }//GEN-LAST:event_jmitem_tabsimActionPerformed

    private void refresh_symtable(final JTable table) {
        Object[][] data = getSimData();
        Object[] headers = getSimHeaders();

        refresh_table(table, data, headers);
    }

    private void refresh_table(final JTable table, Object[][] data, Object[] headers) {
        DefaultTableModel model = (DefaultTableModel) table.getModel();
        model.setDataVector(data, headers);
    }

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void newProMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newProMenuItemActionPerformed
        JFileChooser fchooser = getFChooser();
        fchooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        fchooser.setSelectedFile(null);

        int res = fchooser.showSaveDialog(this);

        if (res == JFileChooser.APPROVE_OPTION) {
            Path dselected = fchooser.getSelectedFile().toPath();
            if (Files.notExists(dselected) || !Files.isDirectory(dselected)) {
                // CREAR PROYECTO...
                String ruta = dselected.toString();
                String nombre = dselected.getFileName().toString();
                String fproject_str = String.format("<proyecto nombre=\"%1$s\" ruta = \"%2$s\"></proyecto>", nombre, ruta);

                try {
                    // Crear directorio
                    Files.createDirectory(dselected);

                    // Crear dir watch
                    //<editor-fold defaultstate="collapsed" desc="thread">
//                    new Thread(() -> {
//                        //??
////                        DefaultTreeModel model = (DefaultTreeModel) jtree_tree.getModel();
////                        synchronized (model) {
////                            DefaultMutableTreeNode root = (DefaultMutableTreeNode) model.getRoot();
////                            DefaultMutableTreeNode child = new DefaultMutableTreeNode(dselected.getFileName());
////                            root.add(child);
////                            model.reload();
////                        }
//
//                        // crear watch
//                        try {
//                            WatchService watcher = FileSystems.getDefault().newWatchService();
//                            dselected.register(watcher, StandardWatchEventKinds.ENTRY_CREATE, StandardWatchEventKinds.ENTRY_DELETE, StandardWatchEventKinds.ENTRY_MODIFY);
//
//                            for (;;) {
//                                // 1.
//                                // wait for key to be signaled
//                                WatchKey key = watcher.take();
//
//                                // 2.
//                                // process
//                                for (WatchEvent<?> event : key.pollEvents()) {
//                                    WatchEvent.Kind<?> kind = event.kind();
//
//                                    // The filename is the
//                                    // context of the event.
//                                    WatchEvent<Path> pevent = (WatchEvent<Path>) event;
//                                    Path p = pevent.context();
//
//                                    boolean endsWith_pj = p.toString().endsWith(".pj");
//                                    boolean endsWith_frc = p.endsWith(".frc");
//
//                                    if (kind == StandardWatchEventKinds.ENTRY_CREATE) {
////                                        if (endsWith_pj) {
////                                            pj_compile(dselected.resolve(p));
////                                        } else if (endsWith_frc) {
////                                        } else {
////                                        }
//                                    } else if (kind == StandardWatchEventKinds.ENTRY_DELETE) {
//                                    } else if (kind == StandardWatchEventKinds.ENTRY_MODIFY) {
//                                        if (endsWith_pj) {
//                                            pj_compile(dselected.resolve(p));
//                                        } else if (endsWith_frc) {
//                                        } else {
//                                        }
//                                    } else {
//                                        // operation not supported...
//                                        System.err.println(p.toAbsolutePath().toString());
//                                        System.err.println(kind.name());
//                                        continue;
//                                    }
//
//                                }
//
//                                // 3.
//                                // Reset the key -- this step is critical if you want to
//                                // receive further watch events.  If the key is no longer valid,
//                                // the directory is inaccessible so exit the loop.
//                                boolean valid = key.reset();
//                                if (!valid) {
//                                    break;
//                                }
//                            }
//                        } catch (IOException ex) {//compiler
//                            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
//                        } catch (InterruptedException ex) {//watch takekey
//                            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
//                        } catch (Exception ex) {
//                            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
//                        }
//
//                    }).start();
                    //</editor-fold>
                    try {
                        System.out.println("Project - creating...");
                        Thread.sleep(500);
                        System.out.println("Project - created...");
                    } catch (InterruptedException ex) {
                        Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
                    }

                    // Crear .pj file
                    final Path fproyecto = dselected.resolve(nombre + ".pj");
                    Files.createFile(fproyecto);

                    // Escribir en .pj file
                    Files.write(fproyecto, fproject_str.getBytes("utf8"));

                    pj_open(fproyecto);

                } catch (IOException ex) {
                    Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
                } catch (Exception ex) {
                    Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }


    }//GEN-LAST:event_newProMenuItemActionPerformed

    private static JFileChooser getFChooser() {
        return new JFileChooser();
    }

    private void openProMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openProMenuItemActionPerformed
        // TODO add your handling code here:
        JFileChooser fChooser = getFChooser();

        fChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fChooser.setFileFilter(new FileNameExtensionFilter("Project File", "pj"));
        fChooser.setMultiSelectionEnabled(true);
        int res = fChooser.showOpenDialog(this);

        if (res == JFileChooser.APPROVE_OPTION) {
            File[] fselected = fChooser.getSelectedFiles();
            for (File f : fselected) {
                try {
                    pj_open(f.toPath());
                } catch (Exception ex) {
                    Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
    }//GEN-LAST:event_openProMenuItemActionPerformed

    private void jmitem_setactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_setactiveActionPerformed
        TreeModel model = getTreeModel();
        synchronized (model) {
            try {
                model.getClass().getField("active").set(model, jtree_tree.getLastSelectedPathComponent());
            } catch (NoSuchFieldException ex) {
                Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SecurityException ex) {
                Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalArgumentException ex) {
                Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_jmitem_setactiveActionPerformed

    private void newMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newMenuItemActionPerformed
        DefaultTreeModel model = getTreeModel();
        // TODO add your handling code here:
        try {

            DefaultMutableTreeNode nodo = tree_project_nodo_active(jtree_tree);
            Pj pj = nodo_project(nodo);

            String res = JOptionPane.showInputDialog("Nombre del archivo .frc:");
            if (!res.trim().isEmpty()) {
                //crear archivo
                Path pnew = Paths.get(pj.getRuta(), res + ".frc");
//                System.err.println(pnew.toString());
                pj.getArchivos().add(pnew.toString());
                Files.createFile(pnew);
                Files.write(Paths.get(pj.getSource()), pj.getXml().getBytes("utf8"));

                synchronized (model) {
                    nodo.add(new DefaultMutableTreeNode(pnew.getFileName().toString()));
                    model.reload(nodo);
                }
            }
        } catch (SecurityException ex) {
            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_newMenuItemActionPerformed

    private static Pj nodo_project(DefaultMutableTreeNode nodo) {
        return (Pj) nodo.getUserObject();
    }

    private DefaultMutableTreeNode tree_project_nodo_active(JTree tree) {
        DefaultMutableTreeNode nodo = null;
        try {
            TreeModel model = tree.getModel();
            final Object obj = model.getClass().getField("active").get(model);
            if (obj == null) {
                throw new UnsupportedOperationException("No hay proyecto activo...");
            }
            nodo = (DefaultMutableTreeNode) obj;
        } catch (NoSuchFieldException ex) {
            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SecurityException ex) {
            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalArgumentException ex) {
            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
        }
        return nodo;

    }

    private void saveMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveMenuItemActionPerformed
        // TODO add your handling code here:

        Dict info = getSelectedTabInfo();

        if (info != null) {
            try {
                Files.write(Paths.get(info.getString("tooltip")), info.getString("text").getBytes("utf8"));
                System.out.println("File Saved..");
            } catch (UnsupportedEncodingException ex) {
                Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }//GEN-LAST:event_saveMenuItemActionPerformed

    private Dict getSelectedTabInfo() {
        int index = jtabbedp_tab.getSelectedIndex();
        if (index >= 0) {
            String tip = jtabbedp_tab.getToolTipTextAt(index);

            JScrollPane spane = (JScrollPane) jtabbedp_tab.getComponentAt(index);

            JEditorPane editor = (JEditorPane) spane.getViewport().getView();
            return new Dict() {
                {
                    put("text", editor.getText());
                    put("tooltip", tip);
                }
            };
        }
        return null;
    }

    private void jmitem_compileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_compileActionPerformed
        // TODO add your handling code here:
        Dict tinfo = getSelectedTabInfo();

        if (tinfo != null) {
            frc_compile(tinfo.getString("text"), compiler_actions, true);
        }
    }//GEN-LAST:event_jmitem_compileActionPerformed

    private void frc_compile(String input, Dict actions, boolean clear) {
        com.github.ceFractal.compiler.fractal.Scanner s = new com.github.ceFractal.compiler.fractal.Scanner(new StringReader(input));
        com.github.ceFractal.compiler.fractal.Parser p = new com.github.ceFractal.compiler.fractal.Parser(s);

        try {
            if (clear) {
                frc_compiler_clear(actions);
            }

            final Symbol sym = p.parse();
            notify("File compiled...");

            if (sym.value != null) {
                final Dict app = (Dict) sym.value;
                frc_compiler_stmts_exec(app, actions);
            }
        } catch (Exception ex) {
            error(ex);
        }
    }

    private void error(Exception ex) {
        Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
    }

    private void notify(Object msg) {
        notify("%s", msg);
    }

    private void notify(String format, Object... msgs) {
        System.err.format(format, msgs);
        System.err.println();

    }

    private void openMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openMenuItemActionPerformed
        // TODO add your handling code here:
        JFileChooser fchooser = getFChooser();

        fchooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        fchooser.setFileFilter(new FileNameExtensionFilter("Frc Files", "frc"));

        int res = fchooser.showOpenDialog(this);
        if (res == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fchooser.getSelectedFile();
            file_open(selectedFile.toPath(), jtabbedp_tab);
        }

    }//GEN-LAST:event_openMenuItemActionPerformed

    private void jmitem_erroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmitem_erroresActionPerformed
        // TODO add your handling code here:
        WinTableDialog wintable = new WinTableDialog(this, false);
        final JTable table = wintable.getJtable_table();

        wintable.getJbutton_refresh().addActionListener((ActionEvent e) -> {
            refresh_errtable(table);
        });

        refresh_errtable(table);

//        wintable.setJtable_table(new JTable(data, headers));
        wintable.setVisible(true);
    }//GEN-LAST:event_jmitem_erroresActionPerformed

    private DefaultTreeModel getTreeModel() {
        return (DefaultTreeModel) jtree_tree.getModel();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Win.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                final Win win = new Win();
                win.setVisible(true);
                win.setSize(800, 600);
                win.jepane_console.setVisible(false);
                win.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenu comilerMenu;
    private javax.swing.JMenuItem contentsMenuItem;
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenuItem cutMenuItem;
    private javax.swing.JMenuItem deleteMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JEditorPane jepane_console;
    private javax.swing.JMenuItem jmitem_compile;
    private javax.swing.JMenuItem jmitem_errores;
    private javax.swing.JMenuItem jmitem_exec;
    private javax.swing.JMenuItem jmitem_setactive;
    private javax.swing.JMenuItem jmitem_tabsim;
    private javax.swing.JPopupMenu jpumenu_pumenu;
    private javax.swing.JScrollPane jsp_tree_scroll;
    private javax.swing.JSplitPane jsplitp_base1;
    private javax.swing.JSplitPane jsplitp_base2;
    private javax.swing.JTabbedPane jtabbedp_tab;
    private javax.swing.JTree jtree_tree;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem newProMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenuItem openProMenuItem;
    private javax.swing.JMenuItem pasteMenuItem;
    private javax.swing.JMenuItem saveAsMenuItem;
    private javax.swing.JMenuItem saveMenuItem;
    // End of variables declaration//GEN-END:variables

    private void myinit() {

        jtree_tree.addMouseListener(new MouseAdapter() {

            @Override
            public void mouseClicked(MouseEvent e) {
                final int x = e.getX();
                final int y = e.getY();
                if (SwingUtilities.isLeftMouseButton(e) && e.getClickCount() == 2) {
                    TreePath tpath = jtree_tree.getPathForLocation(x, y);
                    if (tpath != null && tpath.getPathCount() == 3) {
                        Object obj = tpath.getLastPathComponent();
                        DefaultMutableTreeNode node = (DefaultMutableTreeNode) tpath.getParentPath().getLastPathComponent();

                        Pj pj = nodo_project(node);
                        Path fpath = Paths.get(pj.getRuta(), obj.toString());

                        file_open(fpath, jtabbedp_tab);
                    }
                }
            }

            @Override
            public void mouseReleased(MouseEvent e) {
                final int x = e.getX();
                final int y = e.getY();

                if (e.isPopupTrigger()) {
                    TreePath tpath = jtree_tree.getPathForLocation(x, y);

                    if (tpath != null && tpath.getPathCount() == 2) {
                        jtree_tree.setSelectionPath(tpath);
                        jpumenu_pumenu.show(e.getComponent(), e.getX(), e.getY());
                    }

                }
            }

        });

        jtree_tree.setModel(new DefaultTreeModel(new DefaultMutableTreeNode("PROYECTOS")) {
            public DefaultMutableTreeNode active = null;

        });

        jtree_tree.setCellRenderer(new DefaultTreeCellRenderer() {

            @Override
            public Component getTreeCellRendererComponent(JTree tree, Object value, boolean sel, boolean expanded, boolean leaf, int row, boolean hasFocus) {

                JLabel label = (JLabel) super.getTreeCellRendererComponent(tree, value, sel, expanded, leaf, row, hasFocus); //To change body of generated methods, choose Tools | Templates.

                DefaultMutableTreeNode node = (DefaultMutableTreeNode) value;

                TreeModel model = tree.getModel();

                try {
                    Object get = model.getClass().getField("active").get(model);
                    if (get != null && get.equals(node)) {
                        label.setOpaque(true);
                        label.setBackground(Color.GRAY);
                    } else {
                        label.setOpaque(false);
                        setBackgroundNonSelectionColor(Color.CYAN);
                    }
                } catch (NoSuchFieldException ex) {
                    Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SecurityException ex) {
                    Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalArgumentException ex) {
                    Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IllegalAccessException ex) {
                    Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
                }

                return label;
            }

        });
    }

    private Symbol pj_compile(Path path) throws FileNotFoundException, Exception {

        FileReader freader = new FileReader(path.toString());
        BufferedReader breader = new BufferedReader(freader);

        Scanner s = new Scanner(breader);
        Parser p = new Parser(s);

        return p.parse();

//        System.out.println("Stmts -> " + ((Dict) res.value).getDictArrayList("list").size());
//        pj_process(res);
    }

    private void file_open(Path fpath, JTabbedPane panel) {

        final JTextPane editor = new JTextPane();
        final JScrollPane scroll = new JScrollPane(editor);
        final JTextArea lines = new JTextArea("1");
        scroll.setRowHeaderView(lines);
        editor.setFont(new Font("consolas", Font.PLAIN, 16));
//        setTabSize(editor, 4);
        lines.setBackground(Color.LIGHT_GRAY);
        lines.setFont(editor.getFont());

        String file_text = file_text(fpath);
        editor.setText(file_text);

        panel.addTab(fpath.getFileName().toString(), null, scroll, fpath.toString());
        notify("File opened...");
        if (isFRCFile(fpath)) {
            editor.getDocument().addDocumentListener(new DocumentListener() {

                @Override
                public void insertUpdate(DocumentEvent e) {

                    try {
                        DefaultStyledDocument doc = (DefaultStyledDocument) (StyledDocument) e.getDocument();

                        com.github.ceFractal.compiler.fractal.Scanner s = new com.github.ceFractal.compiler.fractal.Scanner(new StringReader(e.getDocument().getText(0, e.getDocument().getLength() - 1)));

                        SSymbol token;
                        while ((token = s.next_token()) != null) {
                            if (token.sym == Sym.EOF) {
                                break;
                            }
                            SimpleAttributeSet attrs = getTokenStyle(token.sym);

                            final int offset = token.offset;
                            final int length = token.length;

                            SwingUtilities.invokeLater(() -> {
                                doc.setCharacterAttributes(offset, length, attrs, false);
                            });
                        }

                    } catch (IOException ex) {
                        Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
                    } catch (BadLocationException ex) {
                        Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
                    }

//                        DefaultStyledDocument doc = (DefaultStyledDocument) (StyledDocument) e.getDocument();
//
//                        try {
//                            StringBuilder builder = new StringBuilder();
//                            int toffset = 0;
//                            int tlength = 0;
//
//                            for (int i = offset; i >= 0; i--) {
//                                String c = doc.getText(i, 1);
//
//                                if (c.endsWith(" ") || c.endsWith("\t") || c.endsWith("\n")) {
//                                    toffset = i;
//                                    break;
//                                }
//                                builder.append(c);
//
//                            }
//
//                            builder = builder.reverse();
//
//                            for (int i = offset + 1; i < doc.getLength(); i++) {
//                                String c = doc.getText(i, 1);
//
//                                if (c.endsWith(" ") || c.endsWith("\t") || c.endsWith("\n")) {
//                                    break;
//                                }
//                                builder.append(c);
//                            }
//
//                            System.err.println(builder.toString());
//                            com.github.ceFractal.compiler.fractal.Scanner s = new com.github.ceFractal.compiler.fractal.Scanner(new StringReader(builder.toString()));
//
//                            ESymbol token;
//                            while ((token = s.next_token()) != null) {
//                                if (token.sym == Sym.EOF) {
//                                    break;
//                                }
//                                SimpleAttributeSet attrs = new SimpleAttributeSet();
//                                if (token.sym == Sym.ID) {
//                                    StyleConstants.setBold(attrs, true);
//                                    StyleConstants.setForeground(attrs, Color.black);
//
//                                } else if (token.sym == Sym.STRING) {
//                                    StyleConstants.setBold(attrs, false);
//                                    StyleConstants.setForeground(attrs, Color.orange);
//                                } else if (token.sym == Sym.INT) {
//                                    StyleConstants.setBold(attrs, false);
//                                    StyleConstants.setForeground(attrs, Color.blue);
//                                } else {
//                                    StyleConstants.setBold(attrs, false);
//                                    StyleConstants.setForeground(attrs, Color.black);
//                                }
//
//                                SwingUtilities.invokeLater(() -> {
////                                    doc.setCharacterAttributes(roffset, rlength, attrs, false);
//                                });
//                            }
//                        } catch (BadLocationException ex) {
//                            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
//                        } catch (IOException ex) {
//                            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
//                        }
                }

                @Override

                public void removeUpdate(DocumentEvent e) {
                    int offset = e.getOffset();
                    int length = e.getLength();
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    int offset = e.getOffset();
                    int length = e.getLength();

//                        try {
//                            String text = e.getDocument().getText(offset, length);
//                            System.err.println(text);
//                        } catch (BadLocationException ex) {
//                            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
//                        }
                }

                private SimpleAttributeSet getTokenStyle(int sym) {
                    SimpleAttributeSet attrs = new SimpleAttributeSet();
                    switch (sym) {
                        case Sym.INT:
                            getStyle(attrs, Color.BLUE, false, false, false);
                            break;
                        case Sym.FLOAT:
                            getStyle(attrs, Color.BLUE, false, false, false);
                            break;
                        case Sym.CHAR:
                            getStyle(attrs, Color.decode("#90EE90"), false, false, false);
                            break;
                        case Sym.STRING:
                            getStyle(attrs, Color.decode("#006400"), false, false, false);
                            break;
                        case Sym.BOOL:
                            getStyle(attrs, Color.BLUE, false, false, false);
                            break;
                        case Sym.ID:
                            getStyle(attrs, Color.BLACK, true, false, false);
                            break;
                        case Sym.ERROR:
                            getStyle(attrs, Color.RED, false, false, true);
                            break;
                        case Sym.KW_INT:
                            getKWStyle(attrs);
                            break;
                        case Sym.KW_FLOAT:
                            getKWStyle(attrs);
                            break;
                        case Sym.KW_CHAR:
                            getKWStyle(attrs);
                            break;
                        case Sym.KW_STRING:
                            getKWStyle(attrs);
                            break;
                        case Sym.KW_BOOL:
                            getKWStyle(attrs);
                            break;
                        case Sym.KW_VOID:
                            getKWStyle(attrs);
                            break;
                        case Sym.KW_IMPORT:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_CLASS:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_EXTENDS:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_PUBLIC:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_PRIVATE:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_STATIC:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_NEW:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_THIS:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_SUPER:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_ARRAY:
                            getKWStyle2(attrs);
                            break;
                        case Sym.NULL:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_CONTINUE:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_BREAK:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_RETURN:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_FOR:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_WHILE:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_IF:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_ELSE:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_DO:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_SWITCH:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_CASE:
                            getKWStyle2(attrs);
                            break;
                        case Sym.KW_DEFAULT:
                            getKWStyle2(attrs);
                            break;
                        default:
                            getStyle(attrs, Color.BLACK, false, false, false);
                    }

                    return attrs;
                }

                private void getKWStyle2(SimpleAttributeSet attrs) {
                    getStyle(attrs, Color.decode("#00008B"), false, false, false);
                }

                private void getKWStyle(SimpleAttributeSet attrs) {
                    getStyle(attrs, Color.decode("#FF8C00"), false, false, false);
                }

                private void getStyle(SimpleAttributeSet attrs, Color foreground, boolean bold, boolean italic, boolean underline) {
                    StyleConstants.setForeground(attrs, foreground);
                    StyleConstants.setBold(attrs, bold);
                    StyleConstants.setItalic(attrs, italic);
                    StyleConstants.setUnderline(attrs, underline);
                }
            }
            );

        }
    }

    private String file_text(Path fpath) {
        StringBuilder builder = new StringBuilder();

        try {
            List<String> lines = Files.readAllLines(fpath, Charset.forName("utf8"));
            for (String l : lines) {
                builder.append(l);
                builder.append("\n");
            }
//            builder.appsend("\n");
        } catch (IOException ex) {
            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
        }
        return builder.toString();

    }

    private static boolean isFRCFile(Path fpath) {
        return fpath.toString().trim().toLowerCase().endsWith(".frc");
    }

    private Pj symbol2pj(Symbol res) {
        Dict val = (Dict) res.value;

        for (Object obj : val.getDictArrayList("list")) {
            Dict stmt = (Dict) obj;

            String tag = stmt.getString("tag");
            String tagname = stmt.getString("tagname");
            ArrayList<Dict> attr_list = stmt.getDict("attrs").getDictArrayList("list");
            ArrayList<Dict> body_stmt_list = stmt.getDict("body").getDictArrayList("list");

            Dict attrs = attrlist2Dict(attr_list);

//            if (!tag.equalsIgnoreCase("normal")) {
//                throw new UnsupportedOperationException("Etiqueta -> '" + tag + "' no es soportada...");
//            }
            if (!tagname.equalsIgnoreCase("proyecto")) {
                throw new UnsupportedOperationException("El nombre de la etiqueta -> '" + tagname + "' no es valida...");
            }
//
//            if (attr_dict.isEmpty() || !attr_dict.containsKey("nombre") || !attr_dict.containsKey("ruta")) {
//                System.err.println("La de la etiqueta -> '" + tagname + "' no contiene nombre o ruta del proyecto ...");
//                return null;
//            }

            // Procesar stmts de la etiqueta...
            Dict body_dict = unificarTags(body_stmt_list);
//            HashSet<String> body_dict_files, body_dict_main;
//            if (!body_dict.isEmpty()) {
//                //procesar etiqueta archivos
//                body_dict_files = taglist2set(body_dict.getDictArrayList("archivos"), "nombre");
//
//                //procesar etiqueta principal
//                body_dict_main = taglist2set(body_dict.getDictArrayList("principal"), "nombre");
//            }

//            String nombre = attrs.getDict("nombre").getString("val");
//            String ruta = attrs.getDict("ruta").getString("val");
//            pjman.put(attr_dict.getDict("ruta"), pjman.new Pj(nombre, ruta, null, null));
            // updating jtree...
            // Solo se procesara la primera etiqueta...
            return new Pj(
                    (attrs.containsKey("nombre") ? attrs.getString("nombre") : null),
                    (attrs.containsKey("ruta") ? attrs.getString("ruta") : null),
                    (body_dict.containsKey("archivos") ? taglist2set(body_dict.getDictArrayList("archivos"), "nombre") : null),
                    (body_dict.containsKey("principal") ? (taglist2set(body_dict.getDictArrayList("principal"), "nombre").isEmpty() ? null : taglist2set(body_dict.getDictArrayList("principal"), "nombre").iterator().next().toString()) : null)
            );
        }

        return null;
    }

    private Dict attrlist2Dict(ArrayList<Dict> attrlist) {
        Dict ret = new Dict();

        for (Dict attr : attrlist) {
            if (attr.getBoolean("is_attr")) {
                ret.put(attr.getDict("id").get("val").toString(), attr.getDict("val").get("val"));
            }
        }

        return ret;
    }

    private Dict unificarTags(ArrayList<Dict> taglist) {
        Dict ret = new Dict();

        // for each to  this 
//        taglist.stream().filter((tag) -> (tag.getBoolean("is_tag"))).forEach((tag) -> {
//            final String tagname = tag.getString("name");
//            final ArrayList tagbodylist = tag.getDict("body").getDictArrayList("list");
//
//            if (ret.containsKey(tagname)) {
//                ret.getDictArrayList(tagname).addAll(tagbodylist);
//            } else {
//                ret.put(tagname, tagbodylist);
//            }
//        });
        for (Dict tag : taglist) {
            if (tag.getBoolean("is_tag")) {
                final String tagname = tag.getString("tagname").toLowerCase();
                final ArrayList tagbodylist = tag.getDict("body").getDictArrayList("list");

                if (ret.containsKey(tagname)) {
                    ret.getDictArrayList(tagname).addAll(tagbodylist);
                } else {
                    ret.put(tagname, tagbodylist);
                }
            }
        }

        return ret;
    }

    private HashSet<String> taglist2set(ArrayList<Dict> taglist, String attrname) {
        HashSet<String> ret = new HashSet();

        for (Dict tag : taglist) {
            if (tag.getBoolean("is_tag")) {
                Dict attrdict = attrlist2Dict(tag.getDict("attrs").getDictArrayList("list"));
                if (attrdict.containsKey(attrname)) {
                    ret.add(attrdict.getString(attrname));
                }
            }
        }

        return ret;
    }

    private void pj_open(Path p) throws Exception {
        Symbol sym = pj_compile(p);
        Pj pj = symbol2pj(sym);
        pj.setSource(p.toString());

        if (pj == null) {
            throw new UnsupportedOperationException("No existe estructura de proyect en el archivo .pj...");
        }
        if (!pj.isOk()) {
            throw new UnsupportedOperationException("El archivo .pj no contienen información del nombre o ruta del proyecto...");
        }
        Path pruta = Paths.get(pj.getRuta());
        if (!Files.exists(pruta)) {
            throw new UnsupportedOperationException("No existe la ruta -> '" + pj.getRuta() + "'...");
        }
        if (!Files.isDirectory(pruta)) {
            throw new UnsupportedOperationException("No es un directorio la ruta -> '" + pj.getRuta() + "'...");
        }
//        if (pjman.containsKey(pj.getRuta())) {
//            throw new UnsupportedOperationException("Ya existe un proyecto con la ruta -> '" + pj.getRuta() + "'...");
//        }

//        pjman.put(pj.getRuta(), pj);
        System.err.println("ok");

        DefaultTreeModel model = (DefaultTreeModel) getTreeModel();

        synchronized (model) {
            DefaultMutableTreeNode pj_node = new DefaultMutableTreeNode(pj);

            pj.getArchivos().stream().forEach((f) -> {
                DefaultMutableTreeNode f_node = new DefaultMutableTreeNode(Paths.get(f).getFileName());
                pj_node.add(f_node);
            });

            ((DefaultMutableTreeNode) model.getRoot()).add(pj_node);
            model.reload();

        }
    }

    private void frc_compiler_stmts_exec(Dict app, Dict cactions) {
        ArrayList<Dict> stmts = app.getDictArrayList("list");

        for (Dict stmt : stmts) {
            Node nodo = stmt.getNode("nodo");
            if (nodo == null) {
                System.err.println("No Nodo..." + stmt);
                continue;
            }
            nodo.exec(cactions);
        }
    }

    private void frc_compiler_clear(Dict cactions) {
        ((CC) cactions.get("cc")).clear();
    }

    Dict compiler_actions = new Dict(
            "cc", new com.github.gg.CC(),
            "operations", new HashMap<TOperation, Operation>() {
                {
                    put(TOperation.IMPORT, (Operation) (Node node, Object actions) -> {
                        //======================================================
                        // Inicializacion...
                        //======================================================
                        Dict cactions = (Dict) actions;

                        //======================================================
                        // Recopilando informacion necesaria...
                        //======================================================
                        final Dict path = node.getDictRef().getDict("path");
                        final String path_val = path.getString("val");
                        Path path_val_path = Paths.get(path_val);

                        if (!path_val_path.isAbsolute()) {
                            DefaultMutableTreeNode treenode = tree_project_nodo_active(jtree_tree);
                            if (treenode == null) {
                                System.err.println("Not imported...");
                                return null;
                            }

                            Pj pj = nodo_project(treenode);
                            path_val_path = Paths.get(pj.getRuta(), path_val_path.toString());
                        }

                        //======================================================
                        // Compilar archivo import
                        //======================================================
                        frc_compile(file_text(path_val_path), cactions, false);

                        return null;
                    });
                    put(TOperation.DEF_CLASS, (Operation) (Node node, Object actions) -> {
                        //======================================================
                        // Inicializacion...
                        //======================================================
                        Dict cactions = (Dict) actions;
                        CC ccompiler = (CC) cactions.get("cc");

                        //======================================================
                        // Recopilando informacion necesaria...
                        //======================================================
                        Dict _modifiers = node.getDictRef().getDict("modifiers");
                        Dict _name = node.getDictRef().getDict("name");
                        Dict _extends = node.getDictRef().getDict("super");
                        Dict _stmts = node.getDictRef().getDict("stmts");

                        final String _name_val = _name.getString("val");
                        final String _extends_val = (_extends == null ? null : _extends.getString("val"));
                        final HashSet<TModifier> _modifiers_val = (_modifiers == null ? new HashSet<>() : getSetModifiers(_modifiers));

//                        System.err.format("[Name -> %s][Extends -> %s][Modifiers -> %s]\n", _name_val, _extends_val, _modifiers_val.toString());
                        //======================================================
                        //Agregar simbolos
                        //======================================================
                        try {
                            //agregar clase
                            ccompiler.getSims().addClass(_name_val, _extends_val, _modifiers_val);
                            //agregar variable this
//                            ccompiler.getSims().addField(_name_val, new HashSet<TModifier>() {
//                                {
//                                    add(TModifier.PRIVATE);
//                                }
//                            }, _name_val, "this");
                        } catch (UnsupportedOperationException exc) {
                            compiler_error(exc, TErr.SEMANTICO, _name.get("info"), actions);
                        } catch (CloneNotSupportedException ex) {
                            compiler_error(ex, TErr.SEMANTICO, _name.get("info"), actions);
//                            Logger.getLogger(Win.class.getName()).log(Level.SEVERE, null, ex);
                        }

                        //======================================================
                        //Ejecutar sentencias de clase y manejo de ambito...
                        //======================================================
                        /**
                         * scope: Cuando se esta en def_field y def_method es
                         * string Cuando se encuentra dentro de un metodo es el
                         * simbolo del metodo... Mejor que sea solo simbolos que
                         * se maneje... pero si da tiempo...
                         */
                        final Stack scope = new Stack<>();
                        cactions.set("scope", scope);
                        scope.push(_name_val);
                        frc_compiler_stmts_exec(_stmts, cactions);
                        scope.pop();

                        return null;
                    });
                    put(TOperation.DEF_FIELD, (Operation) (Node node, Object actions) -> {
                        //======================================================
                        // Inicializacion...
                        //======================================================
                        Dict cactions = (Dict) actions;
                        CC ccompiler = (CC) cactions.get("cc");
                        Stack<String> stack_scope = cactions.getStack("scope");

                        //======================================================
                        // Recopilando informacion necesaria...
                        //======================================================
                        Dict _modifiers = node.getDictRef().getDict("modifiers");
                        Boolean _array = node.getDictRef().getBoolean("array");
                        Dict _type = node.getDictRef().getDict("type");
                        Dict _name = node.getDictRef().getDict("name");

                        final HashSet<TModifier> _modifiers_val = (_modifiers == null ? new HashSet<>() : getSetModifiers(_modifiers));
                        String _type_val = _type.getString("val");

                        //======================================================
                        // Agregando simbolos...
                        //======================================================
                        for (Dict n : (ArrayList<Dict>) _name.getDictArrayList("list")) {
                            final String n_val = n.getString("val");
                            try {
                                ccompiler.getSims().addField(stack_scope.peek(), _modifiers_val, _type_val, n_val, new Dict("array", (_array == null ? false : _array)));
                            } catch (Exception exc) {
                                compiler_error(exc, TErr.SEMANTICO, n.get("info"), actions);
                            }
                        }

                        return null;
                    });
                    put(TOperation.DEF_METHOD, (Operation) (Node node, Object actions) -> {
                        Dict cactions = (Dict) actions;
                        CC ccompiler = (CC) cactions.get("cc");
                        Stack scope = cactions.getStack("scope");

                        Dict _modifiers = node.getDictRef().getDict("modifiers");
                        Dict _type = node.getDictRef().getDict("type");
                        Dict _name = node.getDictRef().getDict("name");
                        Dict _params = node.getDictRef().getDict("params");
                        Dict _stmts = node.getDictRef().getDict("stmts");

                        final HashSet<TModifier> _modifiers_val = (_modifiers == null ? new HashSet<>() : getSetModifiers(_modifiers));
                        String _type_val = _type.getString("val");
                        String _name_val = _name.getString("val");
                        Object[] _params_type_array = getArrayType(_params);

//                        System.err.println(_modifiers_val);
//                        System.err.println(_type_val);
//                        System.err.println(_name_val);
//                        System.err.println(Arrays.toString(_params_type_array));
                        try {
                            Sim method_sim = ccompiler.getSims().addMethod(scope.peek().toString(), _modifiers_val, _type_val, _name_val, _params_type_array);
                            ccompiler.getSims().addVariable(method_sim, method_sim.scope, "this");
                            cactions.put("method_sim", method_sim);
                        } catch (Exception exc) {
                            compiler_error(exc, TErr.SEMANTICO, _name.get("info"), actions);
                        }

                        //======================================================
                        //Ejecutar sentencias de metodo y manejo de ambito...
                        //======================================================
                        scope.push(_name_val);
                        // ejecutar parametros
                        frc_compiler_stmts_exec(_params, cactions);
                        // ejecutar sentencias
                        frc_compiler_stmts_exec(_stmts, cactions);
                        scope.pop();

                        if (!_type_val.equals(TType.VOID.toString())) {
                        }
                        return null;
                    });
                    put(TOperation.DEF_CONSTRUCT, (Operation) (Node node, Object actions) -> {
                        Dict cactions = (Dict) actions;
                        CC ccompiler = (CC) cactions.get("cc");
                        Stack scope = cactions.getStack("scope");

                        Dict _modifiers = node.getDictRef().getDict("modifiers");
                        Dict _name = node.getDictRef().getDict("name");
                        Dict _params = node.getDictRef().getDict("params");
                        Dict _stmts = node.getDictRef().getDict("stmts");

                        final HashSet<TModifier> _modifiers_val = (_modifiers == null ? new HashSet<>() : getSetModifiers(_modifiers));
                        String _name_val = _name.getString("val");
                        Object[] _params_type_array = getArrayType(_params);

//                        System.err.format("Constructor ->[[Modificadores->%1$s][nombre->%2$s][parametros->%3$s]]\n", _modifiers_val, _name_val, Arrays.toString(_params_type_array));
                        try {
                            Sim method_sim = ccompiler.getSims().addConstruct(scope.peek().toString(), _modifiers_val, _name_val, _params_type_array);
                            ccompiler.getSims().addVariable(method_sim, method_sim.scope, "this");
//                            cactions.put("method_sim", method_sim);

                            //======================================================
                            //Ejecutar sentencias de metodo y manejo de ambito...
                            //======================================================
                            scope.push(method_sim);
                            // ejecutar parametros
                            frc_compiler_stmts_exec(_params, cactions);
                            // ejecutar sentencias
                            frc_compiler_stmts_exec(_stmts, cactions);
                            scope.pop();

                        } catch (Exception exc) {
                            compiler_error(exc, TErr.SEMANTICO, _name.get("info"), actions);
                        }

                        return null;
                    });
                    put(TOperation.DEF_PARAMETER, (Operation) (Node node, Object actions) -> {
                        Dict cactions = (Dict) actions;
                        CC ccompiler = (CC) cactions.get("cc");
                        Stack scope = cactions.getStack("scope");
                        Sim method_sim = (Sim) scope.peek();

                        Boolean _array_val = node.getDictRef().containsKey("array") ? node.getDictRef().getBoolean("array") : false;
                        Dict _ref = node.getDictRef().getDict("ref");
                        Dict _type = node.getDictRef().getDict("type");
                        Dict _name = node.getDictRef().getDict("name");

                        String _ref_val = _ref.getString("val");
                        String _type_val = _type.getString("val");
                        String _name_val = _name.getString("val");

//                        System.err.format("Parametro ->[[ref->%1$s][tipo->%2$s][nombre->%3$s]]\n", _ref_val, _type_val, _name_val);
                        try {
                            ccompiler.getSims().addParameter(method_sim, Boolean.parseBoolean(_ref_val), _type_val, _name_val, new Dict("array", _array_val));
                        } catch (Exception exc) {
                            compiler_error(exc, TErr.SEMANTICO, _name.get("info"), actions);
                        }

                        return null;
                    });
                    put(TOperation.DEF_LOCALVAR, (Operation) (Node node, Object actions) -> {

                        Dict cactions = (Dict) actions;
                        CC ccompiler = (CC) cactions.get("cc");
                        Stack<String> stack_scope = cactions.getStack("scope");
                        Sim method_sim = cactions.getSim("method_sim");

                        Dict _type = node.getDictRef().getDict("type");
                        Dict _name = node.getDictRef().getDict("name");

                        String _type_val = _type.getString("val");

                        //======================================================
                        // Agregando simbolos...
                        //======================================================
                        for (Dict n : (ArrayList<Dict>) _name.getDictArrayList("list")) {
                            final String n_val = n.getString("val");
                            System.err.format("Variable ->[[tipo->%2$s][nombre->%2$s]]\n", _type_val, n_val);

//                            try {
//                                ccompiler.getSims().addVariable(cactions.getSim("method_sim"), _type_val, n_val);
//                            } catch (Exception exc) {
//                                compiler_error(exc, TErr.SEMANTICO, n.get("info"), actions);
//                            }
                        }

                        return null;
                    });
                    put(TOperation.ERROR_LEXICO, (Operation) (Node node, Object cc) -> {
                        compiler_error(new UnsupportedOperationException("Caracter no reconocido..."), TErr.LEXICO, node.getDictRef().get("info"), cc);
                        return null;
                    });
                    put(TOperation.ERROR_SINTACTICO, (Operation) (Node node, Object cc) -> {
                        compiler_error(new UnsupportedOperationException("Error de sintaxis..."), TErr.SINTACTICO, node.getDictRef().get("info"), cc);
                        return null;
                    });
                }

                private void compiler_error(Exception exc, TErr terr, Object info, Object cc) {
                    CC ccompiler = (CC) ((Dict) cc).get("cc");
                    Symbol sym = (Symbol) info;
                    final Err err = new Err(terr, exc.getMessage(), info);
                    ccompiler.getErrs().add(err);

                    System.out.println(err);
//                            error(exc);
                }
            });

    private HashSet getSetModifiers(Dict mod) {
        HashSet<TModifier> ret = new HashSet();
        final ArrayList<Dict> list = mod.getDictArrayList("list");

        for (Dict i : list) {
            ret.add((TModifier) i.get("val"));
        }

        return ret;
    }

    private Object[] getArrayType(Dict params) {
        final ArrayList<Dict> list = (ArrayList<Dict>) params.getDictArrayList("list");
        Object[] ret = new Object[list.size()];
        for (int i = 0; i < list.size(); i++) {
            Dict param = list.get(i);
            ret[i] = param.getDict("type").get("val");
        }
        return ret;
    }

    private Object[][] getSimData() {
        return ((CC) compiler_actions.get("cc")).getSims().toArray2D();
    }

    private Object[] getSimHeaders() {
        return ((CC) compiler_actions.get("cc")).getSims().getArrayHeader();
    }

    private void refresh_errtable(JTable table) {
        Object[][] data = getErrData();
        Object[] headers = getErrHeaders();

        refresh_table(table, data, headers);
    }

    private Object[][] getErrData() {
        return ((CC) compiler_actions.get("cc")).getErrs().toArray2D();
    }

    private Object[] getErrHeaders() {
        return ((CC) compiler_actions.get("cc")).getErrs().getArrayHeader();
    }

    private void setTabSize(JTextPane pane, int i) {
        TabStop[] tabs = new TabStop[i];
        tabs[0] = new TabStop(60, TabStop.ALIGN_LEFT, TabStop.LEAD_NONE);
        tabs[1] = new TabStop(100, TabStop.ALIGN_LEFT, TabStop.LEAD_NONE);
        tabs[2] = new TabStop(200, TabStop.ALIGN_LEFT, TabStop.LEAD_NONE);
        tabs[3] = new TabStop(300, TabStop.ALIGN_LEFT, TabStop.LEAD_NONE);
        TabSet tabset = new TabSet(tabs);

        StyleContext sc = StyleContext.getDefaultStyleContext();
        AttributeSet aset = sc.addAttribute(SimpleAttributeSet.EMPTY,
                StyleConstants.TabSet, tabset);
        pane.setParagraphAttributes(aset, false);
    }

}
